version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: job-crm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: job_crm
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
